# Generated by Django 5.2.7 on 2025-11-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('videocall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='videocall.call'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('call', 'Call'), ('call_missed', 'Missed Call')], default='text', max_length=20),
        ),
    ]
