# Generated by Django 5.2.7 on 2025-11-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_call_message_message_type'),
        ('videocall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.IntegerField(default=0, help_text='Call duration in seconds'),
        ),
        migrations.AddField(
            model_name='call',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
    ]
