# Generated by Django 5.2.7 on 2025-11-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0002_call_chat_call_duration_call_is_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('ended', 'Ended')], default='pending', max_length=10),
        ),
    ]
