# Generated by Django 5.2.7 on 2025-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0003_alter_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('ended', 'Ended')], default='pending', max_length=10),
        ),
    ]
